services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gymshark_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_BACKEND_URL=http://localhost:3001
    restart: unless-stopped
    networks:
      - orders_network

networks:
  orders_network:
    driver: bridge
